apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphacar-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alphacar-backend
  template:
    metadata:
      labels:
        app: alphacar-backend
    spec:
      containers:
      - name: alphacar-backend
        image: 192.168.56.200:30002/alphacar/alphacar-backend:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: alphacar-backend-service
  namespace: default
spec:
  selector:
    app: alphacar-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
